-- Migration: Add AI Notes fields to session_notes table
-- This adds fields for AI-powered session notes: audio recording, transcription, and AI-generated SOAP notes

ALTER TABLE session_notes
ADD COLUMN IF NOT EXISTS audio_recording_url TEXT,
ADD COLUMN IF NOT EXISTS transcription_text TEXT,
ADD COLUMN IF NOT EXISTS de_identified_text TEXT,
ADD COLUMN IF NOT EXISTS ai_generated_note JSONB,
ADD COLUMN IF NOT EXISTS is_ai_generated BOOLEAN DEFAULT FALSE,
ADD COLUMN IF NOT EXISTS ai_processing_status TEXT DEFAULT 'PENDING',
ADD COLUMN IF NOT EXISTS ai_processed_at TIMESTAMPTZ,
ADD COLUMN IF NOT EXISTS therapist_reviewed BOOLEAN DEFAULT FALSE,
ADD COLUMN IF NOT EXISTS therapist_reviewed_at TIMESTAMPTZ,
ADD COLUMN IF NOT EXISTS transcription_status TEXT DEFAULT 'PENDING',
ADD COLUMN IF NOT EXISTS audio_file_size_bytes BIGINT,
ADD COLUMN IF NOT EXISTS audio_duration_seconds INTEGER;

-- Add check constraints for status fields
ALTER TABLE session_notes
DROP CONSTRAINT IF EXISTS session_notes_ai_processing_status_check,
DROP CONSTRAINT IF EXISTS session_notes_transcription_status_check;

ALTER TABLE session_notes
ADD CONSTRAINT session_notes_ai_processing_status_check 
  CHECK (ai_processing_status IN ('PENDING', 'PROCESSING', 'COMPLETED', 'FAILED')),
ADD CONSTRAINT session_notes_transcription_status_check 
  CHECK (transcription_status IN ('PENDING', 'PROCESSING', 'COMPLETED', 'FAILED'));

-- Add indexes for AI notes queries
CREATE INDEX IF NOT EXISTS idx_session_notes_ai_processing_status 
  ON session_notes(ai_processing_status);
CREATE INDEX IF NOT EXISTS idx_session_notes_transcription_status 
  ON session_notes(transcription_status);
CREATE INDEX IF NOT EXISTS idx_session_notes_is_ai_generated 
  ON session_notes(is_ai_generated);
CREATE INDEX IF NOT EXISTS idx_session_notes_therapist_reviewed 
  ON session_notes(therapist_reviewed);

-- Add comments for documentation
COMMENT ON COLUMN session_notes.audio_recording_url IS 'URL to the audio recording stored in Supabase Storage';
COMMENT ON COLUMN session_notes.transcription_text IS 'Raw transcription text from OpenAI Whisper';
COMMENT ON COLUMN session_notes.de_identified_text IS 'De-identified transcription with PHI removed';
COMMENT ON COLUMN session_notes.ai_generated_note IS 'AI-generated SOAP note fields from DeepSeek (JSONB)';
COMMENT ON COLUMN session_notes.is_ai_generated IS 'Whether this note was generated by AI';
COMMENT ON COLUMN session_notes.ai_processing_status IS 'Status of AI processing: PENDING, PROCESSING, COMPLETED, FAILED';
COMMENT ON COLUMN session_notes.transcription_status IS 'Status of transcription: PENDING, PROCESSING, COMPLETED, FAILED';
COMMENT ON COLUMN session_notes.therapist_reviewed IS 'Whether therapist has reviewed the AI-generated note';
